name = "plm-landing-pages"
compatibility_date = "2025-10-03"
pages_build_output_dir = "./public"
compatibility_flags = ["nodejs_compat"]

# Deploy with `wrangler pages deploy ./public --project-name plm-landing --branch main`.
